### ISSUE TITLE
Does not run with jquery 3.1.0

### ISSUE THREAD

**Issue by bm2u** [RickStrahl/jquery-watch#14]
Hi @RickStrahl, after upgrading jQuery from 2.2.4 to 3.1.0 all other plugins run as they were used to. Except jquery-watch. As far as I could evaluate, the code itself runs under 3.1.0 (copied 1:1 into my code). Everything works fine, as long as I keep your code in one of my files. Require the file from node_modules gives the following message and crashes the entire solution.

```
jQuery.Deferred exception: this.$element.children(...).unwatch is not a function TypeError: this.$element.children(...).unwatch is not a function jquery.min.js?7758:2 
Uncaught TypeError: this.$element.children(...).unwatch is not a function
```

Bumping the jquery version in your dependencies to 3.1.0 resolves the issue as well. In my point of view not the best solution.

Any idea? Sláinte, bm2u
